blank_issues_enabled: false
contact_links:
  - name: Help / Questions
    url: https://github.com/Hidden-Alchemy/community/discussions/categories/help
    about: For open-ended questions that are not bugs or features.
